import { createPagesFunctionHandler } from "@react-router/cloudflare";

// @ts-ignore - the server build file is generated by \`react-router build\`
import * as build from "../build/server";
import { getLoadContext } from "../load-context";

export const onRequest = createPagesFunctionHandler({
  build,
  getLoadContext,
});
