name = "utiliti"
workers_dev = true
name = "my-react-router-worker"
compatibility_date = "2024-11-18"
main = "./build/server/index.js"
assets = { directory = "./build/client/" }

[[kv_namespaces]]
binding = "PRIVATE_NOTES"
id = "PRIVATE_NOTES"

[vars]
CF_WHOIS_KEY = "secret"