name = "utiliti"
compatibility_date = "2024-11-11"
compatibility_flags = []
pages_build_output_dir = "./build/client"

[[kv_namespaces]]
binding = "PRIVATE_NOTES"
id = "PRIVATE_NOTES"

[observability]
enabled = true
